// Cas pratiques : entreprises fictives, chiffres en millions de FCFA.
// La trésorerie actif est calculée automatiquement pour équilibrer chaque bilan.

const CASES = [
  {
    id: 'boulangerie',
    short: 'Boulangerie',
    name: 'Boulangerie Le Bon Pain SARL',
    sector: 'Boulangerie-pâtisserie · Abidjan, Cocody',
    level: 'Débutant',
    pitch: 'Une PME rentable qui veut s’agrandir. Est-ce que la banque peut suivre ?',
    context: [
      'Créée en 2014 par Mme Koné, la boulangerie emploie 38 personnes et vend surtout au comptoir (paiement comptant). Environ 15 % des ventes vont à des hôtels et restaurants, payés à 30 jours.',
      'Le matériel est bien entretenu. Le principal fournisseur de farine accorde 45 jours de délai de paiement.',
    ],
    request: {
      amount: 60, kind: 'mlt', years: 5, rate: 0.09,
      object: 'Un four à sole neuf et l’aménagement d’un deuxième point de vente à Angré.',
    },
    years: [2023, 2024, 2025],
    data: [
      { ca: 420, achats: 180, servicesExt: 45, impotsTaxes: 6, chargesPersonnel: 110, dotations: 18, fraisFinanciers: 5, produitsFinanciers: 0, hao: 0, impotResultat: 14,
        immoNettes: 160, stocks: 10, creances: 12, autresCreances: 4, capitauxPropres: 135, dettesFinancieres: 54, fournisseurs: 24, dettesFiscalesSociales: 18, tresoPassif: 0 },
      { ca: 465, achats: 197, servicesExt: 49, impotsTaxes: 7, chargesPersonnel: 120, dotations: 20, fraisFinanciers: 4.5, produitsFinanciers: 0, hao: 0, impotResultat: 17,
        immoNettes: 155, stocks: 11, creances: 13, autresCreances: 4, capitauxPropres: 160, dettesFinancieres: 42, fournisseurs: 26, dettesFiscalesSociales: 20, tresoPassif: 0 },
      { ca: 510, achats: 214, servicesExt: 53, impotsTaxes: 7, chargesPersonnel: 131, dotations: 22, fraisFinanciers: 4, produitsFinanciers: 0.5, hao: 0, impotResultat: 20,
        immoNettes: 150, stocks: 12, creances: 15, autresCreances: 5, capitauxPropres: 190, dettesFinancieres: 30, fournisseurs: 28, dettesFiscalesSociales: 22, tresoPassif: 0 },
    ],
    comments: {
      activite: 'Le CA progresse d’environ 10 % par an et la marge d’EBE reste stable autour de 20 %. Pour une boulangerie, c’est très bon : les prix de vente couvrent largement la farine, l’énergie et les salaires. La croissance est donc rentable.',
      equilibre: 'Le BFR est même négatif : les clients paient comptant et le fournisseur de farine accorde des délais, donc l’exploitation dégage des ressources au lieu d’en consommer. Avec un fonds de roulement positif en plus, on obtient une trésorerie positive qui grossit chaque année. C’est le profil type d’un commerce de détail sain.',
      rotation: 'Les clients paient en une dizaine de jours en moyenne et les stocks tournent vite (produits frais). Le fournisseur finance plus longtemps que ce que durent les stocks et le crédit client : l’activité génère de la trésorerie.',
      endettement: 'La dette financière restante représente moins de six mois de CAF. Même avec le nouveau prêt, l’annuité reste très inférieure à la CAF : le remboursement ne pose aucun problème.',
    },
    best: 'accord',
    decisions: {
      accord: 'Bonne décision. Rentabilité solide, trésorerie positive, endettement très faible : le dossier est bancable. On prendra des garanties classiques, par exemple un nantissement du matériel financé et la domiciliation des recettes.',
      conditions: 'Défendable, mais trop prudent. Rien dans les chiffres ne justifie des conditions lourdes : vous risquez de perdre un bon client au profit d’une banque concurrente. Des garanties standard suffisent.',
      refus: 'Mauvaise décision. Tous les indicateurs sont au vert. Refuser ce dossier, c’est passer à côté d’un client rentable et peu risqué.',
    },
    memo: {
      forces: ['Croissance régulière (+10 %/an) et marge d’EBE d’environ 20 %', 'Trésorerie nette positive et croissante', 'Dette financière inférieure à 6 mois de CAF', 'Fonds propres qui augmentent chaque année (résultats en partie mis en réserve)'],
      faiblesses: ['Dépendance à une dirigeante clé (risque « homme-clé »)', 'Sensibilité au prix de la farine importée', 'Risque d’exécution sur le nouveau point de vente'],
      recommandation: 'Accord de 60 M sur 5 ans. Garanties : nantissement du four, assurance décès-invalidité de la gérante, domiciliation d’une partie des recettes.',
    },
  },
  {
    id: 'transport',
    short: 'TransExpress',
    name: 'TransExpress CI SARL',
    sector: 'Transport et logistique · San-Pédro / Abidjan',
    level: 'Intermédiaire',
    pitch: 'Une croissance spectaculaire… et une trésorerie qui s’effondre. Pourquoi ?',
    context: [
      'Ce transporteur de marchandises (42 camions) a décroché de gros contrats avec des sociétés minières et deux ministères. Le CA a presque doublé en deux ans.',
      'Les clients publics paient souvent à plus de 150 jours. Le gérant demande de porter le découvert autorisé de 150 à 400 M FCFA « pour payer le carburant et les salaires ».',
    ],
    request: {
      amount: 250, kind: 'ct', months: 12, rate: 0.11,
      object: 'Hausse du découvert autorisé de 150 à 400 M FCFA (+250 M).',
    },
    years: [2023, 2024, 2025],
    data: [
      { ca: 600, achats: 250, servicesExt: 90, impotsTaxes: 8, chargesPersonnel: 150, dotations: 45, fraisFinanciers: 12, produitsFinanciers: 0, hao: 0, impotResultat: 13,
        immoNettes: 260, stocks: 20, creances: 165, autresCreances: 12, capitauxPropres: 180, dettesFinancieres: 150, fournisseurs: 60, dettesFiscalesSociales: 28, tresoPassif: 60 },
      { ca: 820, achats: 350, servicesExt: 125, impotsTaxes: 10, chargesPersonnel: 195, dotations: 60, fraisFinanciers: 22, produitsFinanciers: 0, hao: 0, impotResultat: 17,
        immoNettes: 330, stocks: 28, creances: 290, autresCreances: 15, capitauxPropres: 214, dettesFinancieres: 190, fournisseurs: 80, dettesFiscalesSociales: 35, tresoPassif: 150 },
      { ca: 1150, achats: 500, servicesExt: 180, impotsTaxes: 14, chargesPersonnel: 265, dotations: 85, fraisFinanciers: 40, produitsFinanciers: 0, hao: 0, impotResultat: 20,
        immoNettes: 420, stocks: 35, creances: 470, autresCreances: 20, capitauxPropres: 260, dettesFinancieres: 230, fournisseurs: 110, dettesFiscalesSociales: 45, tresoPassif: 310 },
    ],
    comments: {
      activite: 'L’activité est rentable : la marge d’EBE tourne autour de 17 % et le CA progresse de près de 40 % par an. Le problème n’est donc pas la rentabilité. C’est la première chose à retenir : une entreprise rentable peut quand même manquer de cash.',
      equilibre: 'Voici « l’effet ciseaux » : le BFR a plus que triplé (de 109 à 370 M), alors que le fonds de roulement stagne autour de 70 M. La différence est financée par le découvert, et la trésorerie nette s’enfonce à –300 M. Chaque nouveau contrat creuse le trou, parce qu’il faut avancer le carburant et les salaires des mois avant d’être payé.',
      rotation: 'Le délai clients est passé d’environ 100 à environ 150 jours, alors que les fournisseurs (carburant) sont payés en moins de 60 jours. L’entreprise fait crédit à ses clients avec l’argent de la banque, et c’est ce levier qu’il faut traiter.',
      endettement: 'La dette à moyen terme est remboursable en moins de 2 ans de CAF : c’est correct. En revanche, la dette totale (MT + découvert) dépasse deux fois les fonds propres, et un découvert n’est pas fait pour financer un besoin permanent.',
    },
    best: 'conditions',
    decisions: {
      accord: 'Risqué. Augmenter le découvert soigne le symptôme, pas la cause. Si les clients publics paient encore plus tard, le découvert sera de nouveau saturé dans 6 mois et la banque sera piégée avec un encours court terme qui finance en réalité un besoin permanent.',
      conditions: 'Bonne décision. L’activité est rentable, mais le BFR doit être financé par des outils adaptés : mobilisation des créances (escompte, affacturage, avances sur marchés publics), consolidation d’une partie du découvert en crédit à moyen terme, et apport des associés. On encadre le tout avec des covenants sur le délai clients.',
      refus: 'Trop sévère. L’entreprise est rentable et ses clients sont solvables, même s’ils sont lents. Refuser pourrait provoquer une cessation de paiements… et mettre en difficulté l’encours existant de la banque.',
    },
    memo: {
      forces: ['Rentabilité d’exploitation solide (marge d’EBE d’environ 17 %)', 'Carnet de commandes en forte croissance, clients de premier plan', 'Dette MT raisonnable par rapport à la CAF'],
      faiblesses: ['Effet ciseaux : BFR ×3,4 en deux ans, FR stagnant', 'Délai clients d’environ 150 jours, concentré sur des débiteurs publics', 'Trésorerie nette de –300 M, découvert saturé', 'Gearing supérieur à 2'],
      recommandation: 'Accord partiel et restructuré : ligne de mobilisation de créances publiques de 200 M (avances sur marchés domiciliés), consolidation de 100 M de découvert en crédit MT sur 3 ans, apport en compte courant d’associés de 50 M. Covenant : délai clients inférieur à 120 jours d’ici 12 mois.',
    },
  },
  {
    id: 'agro',
    short: 'Agro Négoce',
    name: 'Agro Négoce du Plateau SA',
    sector: 'Négoce de produits vivriers et intrants agricoles · Bouaké',
    level: 'Avancé',
    pitch: 'Un gros chiffre d’affaires, un projet ambitieux… et des signaux faibles à repérer.',
    context: [
      'Grossiste historique de riz, maïs et engrais, la société réalise plus de 2 milliards de FCFA de CA. La concurrence de nouveaux importateurs pèse sur ses prix de vente.',
      'En 2025, elle a vendu un terrain, ce qui a généré une plus-value exceptionnelle (HAO). Le DG présente un plan de relance qui repose sur un nouvel entrepôt frigorifique.',
    ],
    request: {
      amount: 300, kind: 'mlt', years: 7, rate: 0.10,
      object: 'Construction d’un entrepôt frigorifique de 3 000 m² à Bouaké.',
    },
    years: [2023, 2024, 2025],
    data: [
      { ca: 2400, achats: 1950, servicesExt: 170, impotsTaxes: 15, chargesPersonnel: 140, dotations: 55, fraisFinanciers: 60, produitsFinanciers: 2, hao: 0, impotResultat: 4,
        immoNettes: 740, stocks: 420, creances: 350, autresCreances: 30, capitauxPropres: 340, dettesFinancieres: 680, fournisseurs: 280, dettesFiscalesSociales: 45, tresoPassif: 260 },
      { ca: 2250, achats: 1860, servicesExt: 165, impotsTaxes: 15, chargesPersonnel: 145, dotations: 58, fraisFinanciers: 72, produitsFinanciers: 2, hao: 0, impotResultat: 2,
        immoNettes: 720, stocks: 470, creances: 360, autresCreances: 35, capitauxPropres: 275, dettesFinancieres: 650, fournisseurs: 300, dettesFiscalesSociales: 50, tresoPassif: 380 },
      { ca: 2050, achats: 1720, servicesExt: 160, impotsTaxes: 14, chargesPersonnel: 150, dotations: 60, fraisFinanciers: 85, produitsFinanciers: 1, hao: 15, impotResultat: 2,
        immoNettes: 700, stocks: 520, creances: 380, autresCreances: 40, capitauxPropres: 150, dettesFinancieres: 620, fournisseurs: 330, dettesFiscalesSociales: 60, tresoPassif: 520 },
    ],
    comments: {
      activite: 'Ne vous laissez pas impressionner par les 2 milliards de CA. La marge d’EBE s’effondre, de 5,2 % à 0,3 %, et en 2025 l’EBE (6 M) ne couvre même plus les frais financiers (85 M). Sans la plus-value HAO de 15 M, la perte serait encore plus lourde : un produit exceptionnel ne doit jamais masquer la tendance.',
      equilibre: 'Le BFR augmente pendant que le CA baisse : c’est un très mauvais signe, qui évoque des stocks qui ne se vendent plus. Les pertes rongent les fonds propres, qui ont été divisés par plus de deux, et le découvert explose (520 M).',
      rotation: 'Les stocks représentent plus de 100 jours d’achats en 2025, contre environ 78 jours en 2023, pour des produits vivriers périssables ou soumis aux prix du marché. Risque de dépréciation. Les fournisseurs sont payés de plus en plus tard, ce qui peut indiquer une tension sur la trésorerie.',
      endettement: 'La CAF est négative : l’entreprise ne génère plus de ressources pour rembourser quoi que ce soit. Chaque échéance est donc payée avec… de la nouvelle dette. Ajouter 300 M sur 7 ans aggraverait la situation.',
    },
    best: 'refus',
    decisions: {
      accord: 'Décision dangereuse. Avec une CAF négative et des fonds propres qui fondent, l’entreprise ne peut pas rembourser un nouveau prêt de 300 M. Le risque de défaut est très élevé, et la banque ajouterait de l’encours sur un dossier déjà fragile.',
      conditions: 'Insuffisant. Aucune garantie ne remplace une capacité de remboursement : prendre une hypothèque sur l’entrepôt revient à prêter en comptant sur une saisie. Ici, il faut d’abord restructurer.',
      refus: 'Bonne décision. Refus en l’état, mais en proposant une piste : recapitalisation par les actionnaires, plan de réduction des stocks et des coûts, puis réexamen sur la base de comptes redressés. Il faut aussi surveiller de près l’encours existant (classement en « sous surveillance »).',
    },
    memo: {
      forces: ['Acteur historique avec une vraie part de marché', 'Actifs immobiliers mobilisables en garantie'],
      faiblesses: ['CA en baisse de 15 % en deux ans', 'Marge d’EBE passée de 5,2 % à 0,3 %, EBE inférieur aux frais financiers', 'CAF négative : capacité de remboursement nulle', 'Fonds propres divisés par 2,3 à cause des pertes', 'Stocks à plus de 100 jours, découvert de 520 M', 'Résultat 2025 « embelli » par une plus-value HAO'],
      recommandation: 'Refus du financement de 300 M. Proposer un rendez-vous avec les actionnaires : augmentation de capital préalable (au moins 200 M), plan de déstockage et suivi mensuel de la trésorerie. Classer l’encours actuel sous surveillance renforcée.',
    },
  },
  {
    id: 'cacao',
    short: 'Coop cacao',
    name: 'SCOOPS Cacao Espoir de Soubré',
    sector: 'Coopérative de commercialisation de cacao · Soubré',
    level: 'Intermédiaire',
    pitch: 'Une marge de 4 %, un bilan de clôture trompeur : comment financer une campagne ?',
    context: [
      'La coopérative regroupe 1 800 planteurs. Elle achète les fèves à ses membres au prix bord-champ fixé par l’État, les stocke, les trie, puis les revend à un exportateur agréé avec lequel elle a un contrat annuel.',
      'Toute l’activité se concentre sur la grande campagne (octobre à mars). La coopérative doit payer les planteurs comptant à la livraison, alors que l’exportateur paie à l’enlèvement des sacs. Les comptes sont arrêtés en fin de campagne, quand les stocks ont été presque tous vendus.',
    ],
    request: {
      amount: 450, kind: 'ct', months: 8, rate: 0.095,
      object: 'Crédit de campagne de 450 M FCFA sur 8 mois, pour préfinancer l’achat des fèves aux membres.',
      note: 'Remboursement prévu par le produit des ventes à l’exportateur (crédit « auto-liquidatif »).',
    },
    questions: { equilibre: 'fr', rotation: 'dio' },
    years: [2023, 2024, 2025],
    data: [
      { ca: 2600, achats: 2340, servicesExt: 95, impotsTaxes: 8, chargesPersonnel: 60, dotations: 18, fraisFinanciers: 30, produitsFinanciers: 0, hao: 0, impotResultat: 10,
        immoNettes: 180, stocks: 60, creances: 150, autresCreances: 10, capitauxPropres: 210, dettesFinancieres: 70, fournisseurs: 90, dettesFiscalesSociales: 15, tresoPassif: 30 },
      { ca: 2900, achats: 2600, servicesExt: 105, impotsTaxes: 9, chargesPersonnel: 65, dotations: 20, fraisFinanciers: 32, produitsFinanciers: 0, hao: 0, impotResultat: 12,
        immoNettes: 190, stocks: 70, creances: 170, autresCreances: 12, capitauxPropres: 255, dettesFinancieres: 60, fournisseurs: 100, dettesFiscalesSociales: 17, tresoPassif: 30 },
      { ca: 3400, achats: 3050, servicesExt: 120, impotsTaxes: 10, chargesPersonnel: 72, dotations: 22, fraisFinanciers: 36, produitsFinanciers: 0, hao: 0, impotResultat: 15,
        immoNettes: 200, stocks: 80, creances: 190, autresCreances: 14, capitauxPropres: 310, dettesFinancieres: 50, fournisseurs: 110, dettesFiscalesSociales: 20, tresoPassif: 30 },
    ],
    comments: {
      activite: 'Une marge d’EBE d’environ 4 % paraît faible, et la grille de score la pénalise. Pourtant, c’est normal pour une activité de collecte et de négoce : la coopérative gagne peu sur chaque kilo, mais sur de gros volumes. Ce qui compte ici, c’est que la marge soit stable (et même en légère hausse) et que le résultat progresse chaque année.',
      equilibre: 'Le fonds de roulement couvre le BFR constaté à la clôture, et la trésorerie nette est légèrement positive. Attention : le bilan est arrêté en fin de campagne, quand les stocks ont été vendus. En pleine campagne, la coopérative détient des centaines de millions de fèves et doit payer les planteurs comptant. Le vrai besoin de financement est saisonnier : c’est ce pic que le crédit de campagne doit couvrir.',
      rotation: 'À la clôture, le stock ne représente qu’une dizaine de jours d’achats, et l’exportateur paie en une vingtaine de jours. Mais ces ratios annuels lissent la saisonnalité : sur les 6 mois de campagne, les achats représentent environ 500 M par mois. Pour un crédit de campagne, on raisonne donc sur un plan de trésorerie mensuel, pas sur les ratios de fin d’exercice.',
      endettement: 'La CAF (97 M) progresse et la dette à moyen terme est faible. Le coût du crédit de campagne (environ 28 M d’intérêts) est largement couvert par l’EBE. Le vrai risque n’est pas la capacité de remboursement mais le « dénouement » : les fèves financées doivent être vendues et le paiement doit arriver sur le compte de la banque.',
    },
    best: 'accord',
    decisions: {
      accord: 'Bonne décision. Le crédit de campagne est fait pour ce besoin : court, adossé à un stock physique et à un contrat de vente. On le sécurise avec les garanties propres à ce produit : tierce détention ou warrant sur les stocks de fèves, domiciliation irrévocable du paiement de l’exportateur, et déblocage par tranches contre justificatifs d’achat.',
      conditions: 'Acceptable, mais les « conditions » dont ce dossier a besoin sont les garanties standard d’un crédit de campagne (warrant, domiciliation, déblocages par tranches). Ajouter des exigences comme un apport ou une réduction du montant n’est pas justifié par les chiffres.',
      refus: 'Mauvaise décision. Vous avez sans doute été influencé par la marge d’EBE faible ou le score. Mais pour une activité de négoce, 4 % de marge sur des volumes en hausse, des fonds propres qui augmentent et un contrat avec un exportateur font un bon dossier de campagne.',
    },
    memo: {
      forces: ['Volumes et résultat en hausse sur 3 ans', 'Contrat annuel avec un exportateur agréé', 'Fonds propres en croissance, faible dette à moyen terme', 'Crédit auto-liquidatif, adossé à un stock physique'],
      faiblesses: ['Marge unitaire faible : sensibilité à la qualité des fèves (déclassement) et aux coûts logistiques', 'Risque de détournement de fonds ou de stocks pendant la campagne', 'Dépendance à un seul acheteur'],
      recommandation: 'Accord du crédit de campagne de 450 M sur 8 mois. Déblocages par tranches sur présentation des bordereaux d’achat, stocks sous tierce détention (warrant), domiciliation irrévocable des paiements de l’exportateur, suivi hebdomadaire des stocks.',
    },
  },
  {
    id: 'quincaillerie',
    short: 'Quincaillerie',
    name: 'Quincaillerie Bamba & Fils SARL',
    sector: 'Distribution de matériaux de construction · Daloa',
    level: 'Intermédiaire',
    pitch: 'Une entreprise bénéficiaire dont les fonds propres baissent. Où part l’argent ?',
    context: [
      'Entreprise familiale créée il y a 25 ans, leader local de la quincaillerie et des matériaux (ciment, fer, tôles). Elle vend à des particuliers et à de petits entrepreneurs du BTP.',
      'Le fondateur a passé la main à ses deux fils. Ils veulent ouvrir un dépôt à Issia et demandent un prêt. Le banquier remarque que le compte « autres créances » grossit fortement : il s’agit en grande partie d’avances consenties aux associés (compte courant d’associé débiteur).',
    ],
    request: {
      amount: 120, kind: 'mlt', years: 4, rate: 0.10,
      object: 'Construction et stock de départ d’un dépôt à Issia.',
    },
    questions: { rotation: 'dio', endettement: 'gearing' },
    years: [2023, 2024, 2025],
    data: [
      { ca: 720, achats: 540, servicesExt: 40, impotsTaxes: 6, chargesPersonnel: 60, dotations: 12, fraisFinanciers: 10, produitsFinanciers: 0, hao: 0, impotResultat: 8,
        immoNettes: 120, stocks: 150, creances: 60, autresCreances: 20, capitauxPropres: 190, dettesFinancieres: 60, fournisseurs: 80, dettesFiscalesSociales: 15, tresoPassif: 20 },
      { ca: 745, achats: 562, servicesExt: 42, impotsTaxes: 6, chargesPersonnel: 63, dotations: 12, fraisFinanciers: 12, produitsFinanciers: 0, hao: 0, impotResultat: 8,
        immoNettes: 115, stocks: 160, creances: 62, autresCreances: 60, capitauxPropres: 175, dettesFinancieres: 50, fournisseurs: 85, dettesFiscalesSociales: 15, tresoPassif: 75 },
      { ca: 760, achats: 575, servicesExt: 44, impotsTaxes: 7, chargesPersonnel: 66, dotations: 13, fraisFinanciers: 15, produitsFinanciers: 0, hao: 0, impotResultat: 8,
        immoNettes: 110, stocks: 170, creances: 65, autresCreances: 110, capitauxPropres: 150, dettesFinancieres: 40, fournisseurs: 88, dettesFiscalesSociales: 16, tresoPassif: 165 },
    ],
    comments: {
      activite: 'L’activité est stable (+2 à 3 % par an) et rentable : marge d’EBE autour de 9 à 10 %, correcte pour du négoce de matériaux. Elle s’érode un peu, mais rien d’alarmant. Le résultat net reste positif chaque année (44, 40 puis 32 M). Retenez ce point : il va contraster avec la suite.',
      equilibre: 'Le BFR bondit de 135 à 241 M alors que le CA est quasiment stable. D’où vient cette hausse ? Pas des clients (stables), ni vraiment des stocks, mais des « autres créances », passées de 20 à 110 M : de l’argent sorti de l’entreprise au profit des associés. En parallèle, les capitaux propres baissent (190 → 150) malgré des bénéfices : les associés se versent plus que ce que l’entreprise gagne. Résultat : le découvert passe de 20 à 165 M.',
      rotation: 'Le stock représente plus de 100 jours d’achats, ce qui est lourd mais classique en quincaillerie (large gamme d’articles). Le délai clients est raisonnable (environ 31 jours). Le délai de rotation des stocks n’explique donc pas la dégradation de la trésorerie : le problème se trouve dans les prélèvements des associés.',
      endettement: 'La dette à moyen terme est faible, mais le découvert a explosé : la dette nette dépasse désormais les capitaux propres. Surtout, la CAF baisse (56 → 45 M) et le service de la dette, avec le nouveau prêt, dépasserait la CAF. En l’état, l’entreprise ne peut pas rembourser 120 M sur 4 ans sans que l’argent sorti vers les associés revienne.',
    },
    best: 'conditions',
    decisions: {
      accord: 'Risqué. Prêter 120 M alors que 110 M sont sortis de l’entreprise vers les associés, c’est financer indirectement leurs dépenses personnelles. Le service de la dette dépasserait la CAF : l’impayé est probable.',
      conditions: 'Bonne décision. L’activité est saine, mais la gouvernance financière ne l’est pas. Conditions préalables : remboursement d’au moins la moitié du compte courant débiteur, arrêt des distributions pendant la durée du prêt, prêt réduit ou allongé, caution personnelle des associés.',
      refus: 'Défendable mais sévère. Le fonds de commerce est solide et rentable : le problème vient d’un comportement qui peut être corrigé. Un banquier cherche d’abord une solution qui protège la banque tout en gardant le client.',
    },
    memo: {
      forces: ['Leader local, clientèle diversifiée', 'Activité rentable (marge d’EBE d’environ 9 %) et stable', 'Faible dette à moyen terme'],
      faiblesses: ['Compte courant d’associés débiteur de 110 M (sorties de trésorerie non productives)', 'Fonds propres en baisse malgré des bénéfices : distributions supérieures aux résultats', 'Découvert multiplié par 8 en deux ans', 'Service de la dette après le prêt supérieur à la CAF', 'Transmission familiale récente'],
      recommandation: 'Accord sous conditions suspensives : remboursement de 60 M du compte courant débiteur avant déblocage, prêt ramené à 60 M sur 5 ans, engagement de non-distribution pendant 3 ans, caution solidaire des deux associés, hypothèque sur le terrain du dépôt.',
    },
  },
  {
    id: 'clinique',
    short: 'Clinique',
    name: 'Clinique Sainte-Grâce SA',
    sector: 'Santé privée · Yamoussoukro',
    level: 'Avancé',
    pitch: 'Un excellent score… mais que devient-il après le projet ?',
    context: [
      'Clinique pluridisciplinaire de 60 lits, réputée dans la région. Environ 60 % du chiffre d’affaires est payé par des assurances et des mutuelles, qui règlent en moyenne à 3 mois. Le reste est payé comptant par les patients.',
      'La direction veut acheter un scanner et moderniser le bloc opératoire, pour 500 M FCFA. Elle demande de financer 100 % du projet par un prêt bancaire sur 6 ans. Un emprunt antérieur est en cours de remboursement (environ 40 M de capital par an).',
    ],
    request: {
      amount: 500, kind: 'mlt', years: 6, rate: 0.10,
      object: 'Achat d’un scanner et modernisation du bloc opératoire (100 % financé par la banque).',
    },
    questions: { activite: 'va' },
    years: [2023, 2024, 2025],
    data: [
      { ca: 900, achats: 180, servicesExt: 120, impotsTaxes: 12, chargesPersonnel: 380, dotations: 70, fraisFinanciers: 30, produitsFinanciers: 0, hao: 0, impotResultat: 22,
        immoNettes: 820, stocks: 40, creances: 190, autresCreances: 20, capitauxPropres: 480, dettesFinancieres: 410, fournisseurs: 60, dettesFiscalesSociales: 55, tresoPassif: 80 },
      { ca: 980, achats: 196, servicesExt: 130, impotsTaxes: 13, chargesPersonnel: 410, dotations: 75, fraisFinanciers: 28, produitsFinanciers: 0, hao: 0, impotResultat: 24,
        immoNettes: 790, stocks: 42, creances: 225, autresCreances: 22, capitauxPropres: 540, dettesFinancieres: 370, fournisseurs: 64, dettesFiscalesSociales: 58, tresoPassif: 90 },
      { ca: 1050, achats: 210, servicesExt: 140, impotsTaxes: 14, chargesPersonnel: 445, dotations: 80, fraisFinanciers: 26, produitsFinanciers: 0, hao: 0, impotResultat: 26,
        immoNettes: 760, stocks: 45, creances: 265, autresCreances: 25, capitauxPropres: 600, dettesFinancieres: 330, fournisseurs: 68, dettesFiscalesSociales: 62, tresoPassif: 110 },
    ],
    comments: {
      activite: 'La clinique crée beaucoup de valeur ajoutée (environ 67 % du CA) parce que son activité repose sur des compétences (médecins, infirmiers) plus que sur des achats. La marge d’EBE est excellente, autour de 23 %. Les charges de personnel absorbent environ 63 % de la VA : c’est élevé mais normal dans la santé. Rentabilité solide et régulière.',
      equilibre: 'Le BFR augmente plus vite que l’activité : les créances sur les assurances passent de 190 à 265 M. Le fonds de roulement progresse grâce aux bénéfices mis en réserve, et la trésorerie nette, encore négative (la clinique utilise un peu de découvert), s\u2019améliore. Point de vigilance : les délais de paiement des assureurs.',
      rotation: 'Le délai clients passe d’environ 76 à 91 jours. Comme 40 % des patients paient comptant, cela signifie que les assurances paient en réalité à plus de 150 jours. C’est un risque classique des cliniques privées : l’activité est rentable, mais une partie du cash est bloquée chez les assureurs.',
      endettement: 'Avant le projet, tout est au vert : dette / CAF inférieure à 2 ans. Mais un banquier analyse toujours la situation APRÈS le projet. Avec 500 M en plus, la dette atteint environ 4,4 années de CAF, et le service total de la dette (ancien prêt + nouveau) absorbe presque toute la CAF : couverture d’environ 1,05. Aucune marge de sécurité.',
    },
    best: 'conditions',
    decisions: {
      accord: 'Risqué. Le score actuel est excellent, mais il décrit la clinique AVANT le projet. Après le prêt, la CAF couvre à peine le service de la dette : un retard de paiement des assureurs ou une panne du scanner suffirait à créer un impayé.',
      conditions: 'Bonne décision. Le projet est cohérent et la clinique est rentable, mais financer 100 % par la dette est trop tendu. Il faut restructurer : apport de 25 à 30 % en fonds propres, crédit-bail pour le scanner (le matériel sert de garantie), durée portée à 7 ans, et mobilisation des créances sur les assureurs.',
      refus: 'Trop sévère. La clinique est très rentable et le projet augmentera ses revenus. Le problème vient du montage financier, pas de l’entreprise : c’est à la banque de proposer une meilleure structure.',
    },
    memo: {
      forces: ['Marge d’EBE d’environ 23 %, stable', 'Autonomie financière supérieure à 50 %', 'Réputation régionale, demande solide', 'Projet générateur de nouveaux revenus (imagerie)'],
      faiblesses: ['Service total de la dette après le projet ≈ CAF (couverture d’environ 1,05)', 'Dette / CAF passant de 1,8 à 4,4 ans', 'Délais de paiement des assureurs en hausse', 'Risque technologique et de maintenance du scanner'],
      recommandation: 'Accord restructuré : scanner (280 M) en crédit-bail sur 6 ans, prêt de 120 M sur 7 ans pour le bloc, apport des actionnaires de 100 M. Délégation d’assurance, cession de créances sur les principales mutuelles, covenant dette / CAF inférieure à 4.',
    },
  },
];

CASES.forEach(c => { c.data = c.data.map(Engine.balance); });
